#!/usr/bin/env python3
"""
Sky Ace • High-Detail P-38 Sprite Extractor
Extracts and packages the authentic high-detail P-38 sprite sheet generated by nano banana.
"""

import json
from collections import deque
from pathlib import Path
from PIL import Image, ImageDraw
import numpy as np

SPRITES_DIR = Path("games/skyace/sprites")
SPRITES_DIR.mkdir(parents=True, exist_ok=True)
SCRATCH_DIR = Path("scratch")
SCRATCH_DIR.mkdir(parents=True, exist_ok=True)
BRAIN_DIR = Path("/Users/christhompson/.gemini/antigravity-ide/brain/ec418452-c387-4511-87ec-4bed8eda2a62")

SRC_PATH = BRAIN_DIR / "p38_sheet_high_res_1789017952167.jpg"

CELL_SIZE = 256
GRID_COLS = 4
GRID_ROWS = 4

# Cell grid coordinates excluding dividing borders
COL_RANGES = [
    (3, 255),
    (258, 510),
    (514, 765),
    (769, 1020)
]
ROW_RANGES = [
    (3, 255),
    (258, 510),
    (514, 765),
    (769, 1020)
]

def transparentize_cell(cell_img, is_inverted=False):
    """
    Removes the white background using BFS flood-fill from borders and inner hollows,
    preserving the cockpit glass specular glints.
    """
    arr = np.array(cell_img.convert("RGB"))
    h, w, _ = arr.shape
    
    # Background white threshold (RGB > 230)
    is_bg = (arr[:, :, 0] > 230) & (arr[:, :, 1] > 230) & (arr[:, :, 2] > 230)
    
    visited = np.zeros((h, w), dtype=bool)
    q = deque()
    
    # 1. Outer border seeds
    for x in range(w):
        if is_bg[0, x]: q.append((0, x)); visited[0, x] = True
        if is_bg[h-1, x]: q.append((h-1, x)); visited[h-1, x] = True
    for y in range(h):
        if is_bg[y, 0]: q.append((y, 0)); visited[y, 0] = True
        if is_bg[y, w-1]: q.append((y, w-1)); visited[y, w-1] = True
        
    # 2. Inner boom hollow seeds (for upright flight)
    if not is_inverted:
        for sy in [140, 160, 180]:
            for sx in [98, 105, 110, 145, 150, 158]:
                if 0 <= sy < h and 0 <= sx < w and is_bg[sy, sx] and not visited[sy, sx]:
                    visited[sy, sx] = True
                    q.append((sy, sx))
    else:
        # For inverted flight, hollows are in the upper half
        for sy in [70, 90, 110]:
            for sx in [98, 105, 110, 145, 150, 158]:
                if 0 <= sy < h and 0 <= sx < w and is_bg[sy, sx] and not visited[sy, sx]:
                    visited[sy, sx] = True
                    q.append((sy, sx))
                    
    # BFS
    while q:
        y, x = q.popleft()
        for dy, dx in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
            ny, nx = y + dy, x + dx
            if 0 <= ny < h and 0 <= nx < w and not visited[ny, nx]:
                if is_bg[ny, nx]:
                    visited[ny, nx] = True
                    q.append((ny, nx))
                    
    rgba = np.dstack([arr, np.full((h, w), 255, dtype=np.uint8)])
    rgba[visited, 3] = 0
    return Image.fromarray(rgba, "RGBA")

def build_p38_package():
    raw_sheet = Image.open(SRC_PATH)
    
    frame_names = [
        # Row 0
        ("fly_0", 0, 0, False),
        ("fly_1", 0, 1, False),
        ("fly_2", 0, 2, False),
        ("fly_3", 0, 3, False),
        # Row 1
        ("bank_left_1", 1, 0, False),
        ("bank_left_2", 1, 1, False),
        ("bank_right_1", 1, 2, False),
        ("bank_right_2", 1, 3, False),
        # Row 2
        ("pitch_up", 2, 0, False),
        ("knife_edge", 2, 1, False),
        ("dive_apex", 2, 2, True),
        ("skip_x", 2, 3, False),
        # Row 3
        ("dive_inverted", 3, 0, True),
        ("dive_pullout", 3, 1, False),
        ("level_recover", 3, 2, False),
    ]
    
    master_sheet = Image.new("RGBA", (1024, 1024), (0, 0, 0, 0))
    metadata = {
        "meta": {
            "image": "sheet_player_p38.png",
            "size": {"w": 1024, "h": 1024},
            "cell": {"w": CELL_SIZE, "h": CELL_SIZE},
            "cols": 4,
            "rows": 4
        },
        "frames": {}
    }
    
    clean_frames = {}
    
    for name, r, c, is_inv in frame_names:
        if name == "skip_x":
            continue
            
        x0, x1 = COL_RANGES[c]
        y0, y1 = ROW_RANGES[r]
        cell_raw = raw_sheet.crop((x0, y0, x1, y1))
        
        # Transparentize
        trans_cell = transparentize_cell(cell_raw, is_inverted=is_inv)
        
        # Crop tight
        bbox = trans_cell.getbbox()
        if bbox:
            crop = trans_cell.crop(bbox)
        else:
            crop = trans_cell
            
        cw, ch = crop.size
        
        # Paste centered in master cell
        cell_x = c * CELL_SIZE
        cell_y = r * CELL_SIZE
        paste_x = cell_x + (CELL_SIZE - cw) // 2
        paste_y = cell_y + (CELL_SIZE - ch) // 2
        
        master_sheet.paste(crop, (paste_x, paste_y), crop)
        
        # Save individual cell
        clean_cell = Image.new("RGBA", (CELL_SIZE, CELL_SIZE), (0, 0, 0, 0))
        clean_cell.paste(crop, ((CELL_SIZE - cw) // 2, (CELL_SIZE - ch) // 2), crop)
        clean_frames[name] = clean_cell
        clean_cell.save(SCRATCH_DIR / f"highres_p38_{name}.png")
        
        metadata["frames"][name] = {
            "frame": {"x": cell_x, "y": cell_y, "w": CELL_SIZE, "h": CELL_SIZE},
            "sprite": {"x": paste_x, "y": paste_y, "w": cw, "h": ch}
        }
        
    # Save master sheet & metadata
    sheet_dest = SPRITES_DIR / "sheet_player_p38.png"
    json_dest = SPRITES_DIR / "sheet_player_p38.json"
    master_sheet.save(sheet_dest, format="PNG", optimize=True)
    json_dest.write_text(json.dumps(metadata, indent=2), encoding="utf-8")
    
    # Also mirror to brain
    master_sheet.save(BRAIN_DIR / "sheet_player_p38.png", format="PNG", optimize=True)
    print(f"✓ Created master sprite sheet: {sheet_dest}")
    
    # Compile animated preview GIF over Pacific ocean
    build_preview_animation(clean_frames)

def build_preview_animation(frames):
    print("[Sky Ace] Generating preview flight GIF...")
    anim_frames = []
    bg_w, bg_h = 360, 360
    
    sequence = [
        # Idle Cruise (Frames 0, 1, 2, 3)
        ("fly_0", "LEVEL CRUISE"),
        ("fly_1", "LEVEL CRUISE"),
        ("fly_2", "LEVEL CRUISE"),
        ("fly_3", "LEVEL CRUISE"),
        ("fly_0", "LEVEL CRUISE"),
        ("fly_1", "LEVEL CRUISE"),
        ("fly_2", "LEVEL CRUISE"),
        ("fly_3", "LEVEL CRUISE"),
        # Bank Left
        ("bank_left_1", "BANKING LEFT"),
        ("bank_left_2", "HARD BANK LEFT"),
        ("bank_left_2", "HARD BANK LEFT"),
        ("bank_left_1", "BANKING LEFT"),
        ("fly_0", "LEVEL CRUISE"),
        ("fly_1", "LEVEL CRUISE"),
        # Bank Right
        ("bank_right_1", "BANKING RIGHT"),
        ("bank_right_2", "HARD BANK RIGHT"),
        ("bank_right_2", "HARD BANK RIGHT"),
        ("bank_right_1", "BANKING RIGHT"),
        ("fly_2", "LEVEL CRUISE"),
        ("fly_3", "LEVEL CRUISE"),
        # Loop Maneuver
        ("pitch_up", "360° LOOP: PITCH UP"),
        ("knife_edge", "360° LOOP: VERTICAL KNIFE-EDGE"),
        ("dive_apex", "360° LOOP: INVERTED APEX"),
        ("dive_inverted", "360° LOOP: INVERTED DIVE"),
        ("dive_pullout", "360° LOOP: PULLING OUT"),
        ("level_recover", "360° LOOP: LEVEL RECOVERY"),
        # Cruise
        ("fly_0", "LEVEL CRUISE"),
        ("fly_1", "LEVEL CRUISE"),
        ("fly_2", "LEVEL CRUISE"),
        ("fly_3", "LEVEL CRUISE"),
    ]
    
    for frame_idx, (frame_name, label) in enumerate(sequence):
        comp = Image.new("RGBA", (bg_w, bg_h), (22, 64, 118, 255))
        draw = ImageDraw.Draw(comp)
        
        # Scrolling ocean waves
        scroll_y = (frame_idx * 7) % 36
        for wy in range(-36, bg_h + 36, 26):
            y_pos = wy + scroll_y
            for wx in range(0, bg_w, 36):
                draw.arc([wx - 10, y_pos, wx + 10, y_pos + 8], 180, 360, fill=(38, 98, 160, 255), width=2)
                
        # Tropical island
        draw.ellipse([bg_w - 90, 80, bg_w + 30, 200], fill=(42, 160, 170, 255))
        draw.ellipse([bg_w - 75, 95, bg_w + 15, 185], fill=(230, 210, 150, 255))
        draw.ellipse([bg_w - 65, 105, bg_w + 5, 175], fill=(36, 120, 48, 255))
        
        # Fighter
        f_img = frames[frame_name]
        display_size = 140
        f_resized = f_img.resize((display_size, display_size), Image.Resampling.LANCZOS)
        
        # Shadow
        if frame_name not in ["knife_edge", "pitch_up"]:
            shadow = Image.new("RGBA", (display_size, display_size), (0, 0, 0, 0))
            s_pix = shadow.load()
            f_pix = f_resized.load()
            for sx in range(display_size):
                for sy in range(display_size):
                    if f_pix[sx, sy][3] > 0:
                        s_pix[sx, sy] = (10, 24, 48, 80)
            comp.paste(shadow, ((bg_w - display_size) // 2 + 12, (bg_h - display_size) // 2 + 28), shadow)
            
        comp.paste(f_resized, ((bg_w - display_size) // 2, (bg_h - display_size) // 2), f_resized)
        anim_frames.append(comp.convert("RGB"))
        
    gif_path = SCRATCH_DIR / "highres_p38_flight.gif"
    anim_frames[0].save(
        gif_path,
        save_all=True,
        append_images=anim_frames[1:],
        duration=90,
        loop=0,
        optimize=True
    )
    anim_frames[0].save(
        BRAIN_DIR / "highres_p38_flight.gif",
        save_all=True,
        append_images=anim_frames[1:],
        duration=90,
        loop=0,
        optimize=True
    )
    print(f"✓ Saved animation GIF to {gif_path}")

if __name__ == "__main__":
    build_p38_package()
